set_arm_mode:
  name: Set Arm Mode
  description: "Set arming mode for the camera"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera to set recording mode mode for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: securityspy
          domain: camera
    mode:
      name: Armed Mode
      description: "(Required) Valid options are: continuous = Enable/Disable Continuous Recording, on_motion = Enable/Disable motion recording, action = Enable/Disable Actions."
      required: true
      example: on_motion
      selector:
        select:
          options:
            - "continuous"
            - "on_motion"
            - "action"
    enabled:
      name: Enabled
      description: "(Required) True or false"
      required: true
      example: True
      selector:
        boolean:
enable_schedule_preset:
  name: Enable Schedule Preset
  description: "Activate a specific Schedule Preset"
  fields:
    preset_id:
      name: Schedule Preset ID
      description: "The ID of the Schedule Preset to enable. (See Camera Attributes for a list.)"
      required: true
      example: "1214161810"
      selector:
        text:
download_latest_motion_recording:
  name: Download latest motion recording
  description: "Download the latest motion recording video to Home Assistant"
  fields:
    entity_id:
      name: Entity ID
      description: string (required) camera download recording for
      example: "camera.outdoor"
      required: true
      selector:
        entity:
          integration: securityspy
          domain: camera
    filename:
      name: Filename
      description: "Enter directory and filename where to store the video in Home Assistant"
      required: true
      example: "/media/motion_recording.mv4"
      selector:
        text:
